#!/usr/bin/env python3
"""Export a delivered agent for control-plane import (Olympus, Bitter
Blossom): a machine-readable launch contract plus a sprite-shaped persona
file. Pure function of the delivery dir + taskspec, so exports are
reproducible and testable offline.

The persona follows the Bitter Blossom sprite shape (YAML frontmatter:
name/description/model/skills; body = the prompt packet verbatim). Other
control planes consume contract.toml and render their own persona shape.
"""

import subprocess
import sys
import tomllib
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from run import load_candidate  # noqa: E402

CONTRACT_VERSION = 1


def pi_version():
    try:
        out = subprocess.run(["pi", "--version"], capture_output=True,
                             text=True, timeout=30)
        return out.stdout.strip() or "unknown"
    except Exception:  # noqa: BLE001 - version capture is best-effort
        return "unknown"


def _toml_str(value):
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_contract(candidate, spec, harness_version, generated=None):
    budget = spec.get("budget") or {}
    trigger = (spec.get("trigger") or {}).get("intent", "manual runs")
    inputs = (spec.get("inputs") or {}).get("description", "")
    arena = (spec.get("inputs") or {}).get("fixtures", "")
    output = (spec.get("output") or {}).get("contract", "")
    env = candidate.get("env_allowlist", ["OPENROUTER_API_KEY"])
    generated = generated or datetime.now(timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    )
    tools = ", ".join(_toml_str(t) for t in candidate.get("tools") or [])
    env_s = ", ".join(_toml_str(e) for e in env)
    return f"""\
# Launch contract — generated by daedalus export; do not hand-edit fields
# that are pinned to evidence (composition_hash, harness_version).
contract = {CONTRACT_VERSION}
generated = {_toml_str(generated)}
agent = {_toml_str(candidate["id"])}
composition_hash = {_toml_str(candidate["_hash"])}
taskspec = {_toml_str(spec.get("id", ""))}
mode = {_toml_str(spec.get("mode", ""))}

[composition]
harness = {_toml_str(candidate["kind"])}
harness_version = {_toml_str(harness_version)}
provider = {_toml_str(candidate.get("provider_name", "openrouter"))}
model = {_toml_str(candidate.get("model", ""))}
thinking = {_toml_str(candidate.get("thinking", ""))}
tools = [{tools}]
prompt_packet = {_toml_str(candidate.get("prompt_packet", ""))}
system_prompt_mode = {_toml_str(candidate.get("system_prompt_mode", "append"))}
timeout_sec = {candidate.get("timeout_sec", 600)}

[trigger]
intent = {_toml_str(trigger)}

[inputs]
description = {_toml_str(inputs)}

[output]
contract = {_toml_str(output)}

[permissions]
workspace = "read-only checkout; writes only the output artifact in a throwaway workdir"
env = [{env_s}]
write_actions = "none — outputs are advisory until gate G4 grants more"

[budgets]
max_cost_usd_per_run = {budget.get("max_cost_per_trial_usd", 0.5)}
max_wall_sec = {budget.get("max_wall_per_trial_sec", 600)}

[escalation]
on_malformed_output = "emit nothing; flag the run for human review"
on_timeout = "emit nothing; flag the run for human review"

[observability]
trace_destination = "TBD (Langfuse, backlog 014); JSONL run records are canonical"
regression_eval = "re-run the arena holdout on any packet/model/harness change, and on a monthly cadence"
arena = {_toml_str(arena)}

[approval]
g3_signed = false
note = "Do not deploy until approvals/G3-{candidate["id"]}.md is signed by a human."
"""


def render_persona(candidate, spec):
    """Bitter Blossom sprite shape: frontmatter + the packet verbatim as the
    body, so the deployed system prompt is byte-identical to the measured
    one (the composition hash covers exactly this text)."""
    goal = (spec.get("goal") or "").strip()
    description = goal if len(goal) <= 160 else goal[:157] + "..."
    skills = "\n".join(f"  - {s}" for s in candidate.get("skills") or [])
    skills_block = f"skills:\n{skills}" if skills else "skills: []"
    body = candidate.get("_packet_text") or ""
    return (
        "---\n"
        f"name: {candidate['id']}\n"
        f'description: "{description}"\n'
        f"model: {candidate.get('provider_name', 'openrouter')}/"
        f"{candidate.get('model', '')}\n"
        f"{skills_block}\n"
        "daedalus:\n"
        f"  composition_hash: {candidate['_hash']}\n"
        "  contract: contract.toml\n"
        "---\n\n"
        + body
    )


def export_delivery(delivery_dir, spec, harness_version=None, generated=None):
    """Write contract.toml and persona.md next to the delivery's agent.toml.
    Returns {contract, persona} paths."""
    delivery_dir = Path(delivery_dir)
    candidate = load_candidate(delivery_dir / "agent.toml")
    harness_version = harness_version or pi_version()
    contract_text = render_contract(candidate, spec, harness_version,
                                    generated=generated)
    tomllib.loads(contract_text)  # the exported artifact must parse
    contract_path = delivery_dir / "contract.toml"
    contract_path.write_text(contract_text)
    persona_path = delivery_dir / "persona.md"
    persona_path.write_text(render_persona(candidate, spec))
    return {"contract": contract_path, "persona": persona_path}
